
using System.Diagnostics;
using System.Drawing;
using Sandbox.Common.Registry;
using Sandbox.Common.Worlds.Items;

public static class DyeHardItems
{
  public static Registry<Item> ITEMS = Registries.Get<Item>(BuiltInRegistries.ITEM);



  public static Item ALICE_BLUE_DYE = ITEMS.Register("dyehard:alice_blue_dye", new DyeItem(Color.AliceBlue));
  public static Item ANTIQUE_WHITE_DYE = ITEMS.Register("dyehard:antique_white_dye", new DyeItem(Color.AntiqueWhite));
  public static Item AQUAMARINE_DYE = ITEMS.Register("dyehard:aquamarine_dye", new DyeItem(Color.Aquamarine));
  public static Item AZURE_DYE = ITEMS.Register("dyehard:azure_dye", new DyeItem(Color.Azure));
  public static Item BEIGE_DYE = ITEMS.Register("dyehard:beige_dye", new DyeItem(Color.Beige));
  public static Item BISQUE_DYE = ITEMS.Register("dyehard:bisque_dye", new DyeItem(Color.Bisque));
  public static Item BLACK_DYE = ITEMS.Register("dyehard:black_dye", new DyeItem(Color.Black));
  public static Item BLANCHED_ALMOND_DYE = ITEMS.Register("dyehard:blanched_almond_dye", new DyeItem(Color.BlanchedAlmond));
  public static Item BLUE_DYE = ITEMS.Register("dyehard:blue_dye", new DyeItem(Color.Blue));
  public static Item BLUE_VIOLET_DYE = ITEMS.Register("dyehard:blue_violet_dye", new DyeItem(Color.BlueViolet));
  public static Item BROWN_DYE = ITEMS.Register("dyehard:brown_dye", new DyeItem(Color.Brown));
  public static Item BURLY_WOOD_DYE = ITEMS.Register("dyehard:burly_wood_dye", new DyeItem(Color.BurlyWood));
  public static Item CADET_BLUE_DYE = ITEMS.Register("dyehard:cadet_blue_dye", new DyeItem(Color.CadetBlue));
  public static Item CHARTREUSE_DYE = ITEMS.Register("dyehard:chartreuse_dye", new DyeItem(Color.Chartreuse));
  public static Item CHOCOLATE_DYE = ITEMS.Register("dyehard:chocolate_dye", new DyeItem(Color.Chocolate));
  public static Item CORAL_DYE = ITEMS.Register("dyehard:coral_dye", new DyeItem(Color.Coral));
  public static Item CORNFLOWER_BLUE_DYE = ITEMS.Register("dyehard:cornflower_blue_dye", new DyeItem(Color.CornflowerBlue));
  public static Item CORNSILK_DYE = ITEMS.Register("dyehard:cornsilk_dye", new DyeItem(Color.Cornsilk));
  public static Item CRIMSON_DYE = ITEMS.Register("dyehard:crimson_dye", new DyeItem(Color.Crimson));
  public static Item CYAN_DYE = ITEMS.Register("dyehard:cyan_dye", new DyeItem(Color.Cyan));
  public static Item DARK_BLUE_DYE = ITEMS.Register("dyehard:dark_blue_dye", new DyeItem(Color.DarkBlue));
  public static Item DARK_CYAN_DYE = ITEMS.Register("dyehard:dark_cyan_dye", new DyeItem(Color.DarkCyan));
  public static Item DARK_GOLDENROD_DYE = ITEMS.Register("dyehard:dark_goldenrod_dye", new DyeItem(Color.DarkGoldenrod));
  public static Item DARK_GRAY_DYE = ITEMS.Register("dyehard:dark_gray_dye", new DyeItem(Color.DarkGray));
  public static Item DARK_GREEN_DYE = ITEMS.Register("dyehard:dark_green_dye", new DyeItem(Color.DarkGreen));
  public static Item DARK_KHAKI_DYE = ITEMS.Register("dyehard:dark_khaki_dye", new DyeItem(Color.DarkKhaki));
  public static Item DARK_MAGENTA_DYE = ITEMS.Register("dyehard:dark_magenta_dye", new DyeItem(Color.DarkMagenta));
  public static Item DARK_OLIVE_GREEN_DYE = ITEMS.Register("dyehard:dark_olive_green_dye", new DyeItem(Color.DarkOliveGreen));
  public static Item DARK_ORANGE_DYE = ITEMS.Register("dyehard:dark_orange_dye", new DyeItem(Color.DarkOrange));
  public static Item DARK_ORCHID_DYE = ITEMS.Register("dyehard:dark_orchid_dye", new DyeItem(Color.DarkOrchid));
  public static Item DARK_RED_DYE = ITEMS.Register("dyehard:dark_red_dye", new DyeItem(Color.DarkRed));
  public static Item DARK_SALMON_DYE = ITEMS.Register("dyehard:dark_salmon_dye", new DyeItem(Color.DarkSalmon));
  public static Item DARK_SEA_GREEN_DYE = ITEMS.Register("dyehard:dark_sea_green_dye", new DyeItem(Color.DarkSeaGreen));
  public static Item DARK_SLATE_BLUE_DYE = ITEMS.Register("dyehard:dark_slate_blue_dye", new DyeItem(Color.DarkSlateBlue));
  public static Item DARK_SLATE_GRAY_DYE = ITEMS.Register("dyehard:dark_slate_gray_dye", new DyeItem(Color.DarkSlateGray));
  public static Item DARK_TURQUOISE_DYE = ITEMS.Register("dyehard:dark_turquoise_dye", new DyeItem(Color.DarkTurquoise));
  public static Item DARK_VIOLET_DYE = ITEMS.Register("dyehard:dark_violet_dye", new DyeItem(Color.DarkViolet));
  public static Item DEEP_PINK_DYE = ITEMS.Register("dyehard:deep_pink_dye", new DyeItem(Color.DeepPink));
  public static Item DEEP_SKY_BLUE_DYE = ITEMS.Register("dyehard:deep_sky_blue_dye", new DyeItem(Color.DeepSkyBlue));
  public static Item DIM_GRAY_DYE = ITEMS.Register("dyehard:dim_gray_dye", new DyeItem(Color.DimGray));
  public static Item DODGER_BLUE_DYE = ITEMS.Register("dyehard:dodger_blue_dye", new DyeItem(Color.DodgerBlue));
  public static Item FIREBRICK_DYE = ITEMS.Register("dyehard:firebrick_dye", new DyeItem(Color.Firebrick));
  public static Item FLORAL_WHITE_DYE = ITEMS.Register("dyehard:floral_white_dye", new DyeItem(Color.FloralWhite));
  public static Item FOREST_GREEN_DYE = ITEMS.Register("dyehard:forest_green_dye", new DyeItem(Color.ForestGreen));
  public static Item GAINSBORO_DYE = ITEMS.Register("dyehard:gainsboro_dye", new DyeItem(Color.Gainsboro));
  public static Item GHOST_WHOTE_DYE = ITEMS.Register("dyehard:ghost_white_dye", new DyeItem(Color.GhostWhite));
  public static Item GOLD_DYE = ITEMS.Register("dyehard:gold_dye", new DyeItem(Color.Gold));
  public static Item GOLDENROD_DYE = ITEMS.Register("dyehard:goldenrod_dye", new DyeItem(Color.Goldenrod));
  public static Item GRAY_DYE = ITEMS.Register("dyehard:gray_dye", new DyeItem(Color.Gray));
  public static Item GREEN_DYE = ITEMS.Register("dyehard:green_dye", new DyeItem(Color.Green));
  public static Item GREEN_YELLOW_DYE = ITEMS.Register("dyehard:green_yellow_dye", new DyeItem(Color.GreenYellow));
  public static Item HONEYDEW_DYE = ITEMS.Register("dyehard:honeydew_dye", new DyeItem(Color.Honeydew));
  public static Item HOT_PINK_DYE = ITEMS.Register("dyehard:hot_pink_dye", new DyeItem(Color.HotPink));
  public static Item INDIAN_RED_DYE = ITEMS.Register("dyehard:indian_red_dye", new DyeItem(Color.IndianRed));
  public static Item INDIGO_DYE = ITEMS.Register("dyehard:indigo_dye", new DyeItem(Color.Indigo));
  public static Item IVORY_DYE = ITEMS.Register("dyehard:ivory_dye", new DyeItem(Color.Ivory));
  public static Item KHAKI_DYE = ITEMS.Register("dyehard:khaki_dye", new DyeItem(Color.Khaki));
  public static Item LAVENDER_DYE = ITEMS.Register("dyehard:lavender_dye", new DyeItem(Color.Lavender));
  public static Item LAVENDER_BLUSH_DYE = ITEMS.Register("dyehard:lavender_blush_dye", new DyeItem(Color.LavenderBlush));
  public static Item LAWN_GREEN_DYE = ITEMS.Register("dyehard:lawn_green_dye", new DyeItem(Color.LawnGreen));
  public static Item LEMON_CHIFFRON_DYE = ITEMS.Register("dyehard:lemon_chiffon_dye", new DyeItem(Color.LemonChiffon));
  public static Item LIGHT_BLUE_DYE = ITEMS.Register("dyehard:light_blue_dye", new DyeItem(Color.LightBlue));
  public static Item LIGHT_CORAL_DYE = ITEMS.Register("dyehard:light_coral_dye", new DyeItem(Color.LightCoral));
  public static Item LIGHT_CYAN_DYE = ITEMS.Register("dyehard:light_cyan_dye", new DyeItem(Color.LightCyan));
  public static Item LIGHT_GOLDENROD_YELLOW_DYE = ITEMS.Register("dyehard:light_goldenrod_yellow_dye", new DyeItem(Color.LightGoldenrodYellow));
  public static Item LIGHT_GRAY_DYE = ITEMS.Register("dyehard:light_gray_dye", new DyeItem(Color.LightGray));
  public static Item LIGHT_GREEN_DYE = ITEMS.Register("dyehard:light_green_dye", new DyeItem(Color.LightGreen));
  public static Item LIGHT_PINK_DYE = ITEMS.Register("dyehard:light_pink_dye", new DyeItem(Color.LightPink));
  public static Item LIGHT_SALMON_DYE = ITEMS.Register("dyehard:light_salmon_dye", new DyeItem(Color.LightSalmon));
  public static Item LIGHT_SEA_GREEN_DYE = ITEMS.Register("dyehard:light_sea_green_dye", new DyeItem(Color.LightSeaGreen));
  public static Item LIGHT_SKY_BLUE_DYE = ITEMS.Register("dyehard:light_sky_blue_dye", new DyeItem(Color.LightSkyBlue));
  public static Item LIGHT_SLATE_GRAY_DYE = ITEMS.Register("dyehard:light_slate_gray_dye", new DyeItem(Color.LightSlateGray));
  public static Item LIGHT_STEEL_BLUE_DYE = ITEMS.Register("dyehard:light_steel_blue_dye", new DyeItem(Color.LightSteelBlue));
  public static Item LIGHT_YELLOW_DYE = ITEMS.Register("dyehard:light_yellow_dye", new DyeItem(Color.LightYellow));
  public static Item LIME_DYE = ITEMS.Register("dyehard:lime_dye", new DyeItem(Color.Lime));
  public static Item LIME_GREEN_DYE = ITEMS.Register("dyehard:lime_green_dye", new DyeItem(Color.LimeGreen));
  public static Item LINEN_DYE = ITEMS.Register("dyehard:linen_dye", new DyeItem(Color.Linen));
  public static Item MAGENTA_DYE = ITEMS.Register("dyehard:magenta_dye", new DyeItem(Color.Magenta));
  public static Item MAROON_DYE = ITEMS.Register("dyehard:maroon_dye", new DyeItem(Color.Maroon));
  public static Item MEDIUM_AQUAMARINE_DYE = ITEMS.Register("dyehard:medium_aquamarine_dye", new DyeItem(Color.MediumAquamarine));
  public static Item MEDIUM_BLUE_DYE = ITEMS.Register("dyehard:medium_blue_dye", new DyeItem(Color.MediumBlue));
  public static Item MEDIUM_ORCHID_DYE = ITEMS.Register("dyehard:medium_orchid_dye", new DyeItem(Color.MediumOrchid));
  public static Item MEDIUM_PURPLE_DYE = ITEMS.Register("dyehard:medium_purple_dye", new DyeItem(Color.MediumPurple));
  public static Item MEDIUM_SEA_GREEN_DYE = ITEMS.Register("dyehard:medium_sea_green_dye", new DyeItem(Color.MediumSeaGreen));
  public static Item MEDIUM_SLATE_BLUE_DYE = ITEMS.Register("dyehard:medium_slate_blue_dye", new DyeItem(Color.MediumSlateBlue));
  public static Item MEDIUM_SPRING_GREEN_DYE = ITEMS.Register("dyehard:medium_spring_green_dye", new DyeItem(Color.MediumSpringGreen));
  public static Item MEDIUM_TURQUOISE_DYE = ITEMS.Register("dyehard:medium_turqoise_dye", new DyeItem(Color.MediumTurquoise));
  public static Item MEDIUM_VIOLET_RED_DYE = ITEMS.Register("dyehard:medium_violet_red_dye", new DyeItem(Color.MediumVioletRed));
  public static Item MIDNIGHT_BLUE_DYE = ITEMS.Register("dyehard:midnight_blue_dye", new DyeItem(Color.MidnightBlue));
  public static Item MINT_CREAM_DYE = ITEMS.Register("dyehard:mint_cream_dye", new DyeItem(Color.MintCream));
  public static Item MISTY_ROSE_DYE = ITEMS.Register("dyehard:misty_rose_dye", new DyeItem(Color.MistyRose));
  public static Item MOCCASIN_DYE = ITEMS.Register("dyehard:moccasin_dye", new DyeItem(Color.Moccasin));
  public static Item NAVAJO_WHITE_DYE = ITEMS.Register("dyehard:navajo_white_dye", new DyeItem(Color.NavajoWhite));
  public static Item NAVY_DYE = ITEMS.Register("dyehard:navy_dye", new DyeItem(Color.Navy));
  public static Item OLD_LACE_DYE = ITEMS.Register("dyehard:old_lace_dye", new DyeItem(Color.OldLace));
  public static Item OLIVE_DYE = ITEMS.Register("dyehard:olive_dye", new DyeItem(Color.Olive));
  public static Item OLIVE_DRAB_DYE = ITEMS.Register("dyehard:olive_drab_dye", new DyeItem(Color.OliveDrab));
  public static Item ORANGE_DYE = ITEMS.Register("dyehard:orange_dye", new DyeItem(Color.Orange));
  public static Item ORANGE_RED_DYE = ITEMS.Register("dyehard:orange_red_dye", new DyeItem(Color.OrangeRed));
  public static Item ORCHID_DYE = ITEMS.Register("dyehard:orchid_dye", new DyeItem(Color.Orchid));
  public static Item PALE_GOLDENROD_DYE = ITEMS.Register("dyehard:pale_goldenrod_dye", new DyeItem(Color.PaleGoldenrod));
  public static Item PALE_GREEN_DYE = ITEMS.Register("dyehard:pale_green_dye", new DyeItem(Color.PaleGreen));
  public static Item PALE_TURQUOISE_DYE = ITEMS.Register("dyehard:pale_turquoise_dye", new DyeItem(Color.PaleTurquoise));
  public static Item PALE_VIOLET_RED_DYE = ITEMS.Register("dyehard:pale_violet_red_dye", new DyeItem(Color.PaleVioletRed));
  public static Item PAPAYA_WHIP_DYE = ITEMS.Register("dyehard:papaya_whip_dye", new DyeItem(Color.PapayaWhip));
  public static Item PEACH_PUFF_DYE = ITEMS.Register("dyehard:peach_puff_dye", new DyeItem(Color.PeachPuff));
  public static Item PERU_DYE = ITEMS.Register("dyehard:peru_dye", new DyeItem(Color.Peru));
  public static Item PINK_DYE = ITEMS.Register("dyehard:pink_dye", new DyeItem(Color.Pink));
  public static Item PLUM_DYE = ITEMS.Register("dyehard:plum_dye", new DyeItem(Color.Plum));
  public static Item POWDER_BLUE_DYE = ITEMS.Register("dyehard:powder_blue_dye", new DyeItem(Color.PowderBlue));
  public static Item PURPLE_DYE = ITEMS.Register("dyehard:purple_dye", new DyeItem(Color.Purple));
  public static Item RED_DYE = ITEMS.Register("dyehard:red_dye", new DyeItem(Color.Red));
  public static Item ROSY_BROWN_DYE = ITEMS.Register("dyehard:rosy_brown_dye", new DyeItem(Color.RosyBrown));
  public static Item ROYAL_BLUE_DYE = ITEMS.Register("dyehard:royal_blue_dye", new DyeItem(Color.RoyalBlue));
  public static Item SADDLE_BROWN_DYE = ITEMS.Register("dyehard:saddle_brown_dye", new DyeItem(Color.SaddleBrown));
  public static Item SALMON_DYE = ITEMS.Register("dyehard:salmon_dye", new DyeItem(Color.Salmon));
  public static Item SANDY_BROWN_DYE = ITEMS.Register("dyehard:sandy_brown_dye", new DyeItem(Color.SandyBrown));
  public static Item SEA_GREEN_DYE = ITEMS.Register("dyehard:sea_green_dye", new DyeItem(Color.SeaGreen));
  public static Item SEA_SHELL_DYE = ITEMS.Register("dyehard:sea_shell_dye", new DyeItem(Color.SeaShell));
  public static Item SIENNA_DYE = ITEMS.Register("dyehard:sienna_dye", new DyeItem(Color.Sienna));
  public static Item SILVER_DYE = ITEMS.Register("dyehard:silver_dye", new DyeItem(Color.Silver));
  public static Item SKY_BLUE_DYE = ITEMS.Register("dyehard:sky_blue_dye", new DyeItem(Color.SkyBlue));
  public static Item SLATE_BLUE_DYE = ITEMS.Register("dyehard:slate_blue_dye", new DyeItem(Color.SlateBlue));
  public static Item SLATE_GRAY_DYE = ITEMS.Register("dyehard:slate_gray_dye", new DyeItem(Color.SlateGray));
  public static Item SNOW_DYE = ITEMS.Register("dyehard:snow_dye", new DyeItem(Color.Snow));
  public static Item SPRING_GREEN_DYE = ITEMS.Register("dyehard:spring_green_dye", new DyeItem(Color.SpringGreen));
  public static Item STEEL_BLUE_DYE = ITEMS.Register("dyehard:steel_blue_dye", new DyeItem(Color.SteelBlue));
  public static Item TAN_DYE = ITEMS.Register("dyehard:tan_dye", new DyeItem(Color.Tan));
  public static Item TEAL_DYE = ITEMS.Register("dyehard:teal_dye", new DyeItem(Color.Teal));
  public static Item THISTLE_DYE = ITEMS.Register("dyehard:thistle_dye", new DyeItem(Color.Thistle));
  public static Item TOMATO_DYE = ITEMS.Register("dyehard:tomato_dye", new DyeItem(Color.Tomato));
  public static Item TURQUOISE_DYE = ITEMS.Register("dyehard:turquoise_dye", new DyeItem(Color.Turquoise));
  public static Item VIOLET_DYE = ITEMS.Register("dyehard:violet_dye", new DyeItem(Color.Violet));
  public static Item WHEAT_DYE = ITEMS.Register("dyehard:wheat_dye", new DyeItem(Color.Wheat));
  public static Item WHITE_DYE = ITEMS.Register("dyehard:white_dye", new DyeItem(Color.White));
  public static Item WHITE_SMOKE_DYE = ITEMS.Register("dyehard:white_smoke_dye", new DyeItem(Color.WhiteSmoke));
  public static Item YELLOW_DYE = ITEMS.Register("dyehard:yellow_dye", new DyeItem(Color.Yellow));
  public static Item YELLOW_GREEN_DYE = ITEMS.Register("dyehard:yellow_green_dye", new DyeItem(Color.YellowGreen));


  public static Item REBECCA_PURPLE_DYE = ITEMS.Register("dyehard:rebecca_purple_dye", new DyeItem(Color.RebeccaPurple));

  public static void Init()
  {
    Debug.Print("DyeHardItems static constructor");
  }
}